language: python
cache: pip
dist: xenial

env:
  global:
    - PYTHONUNBUFFERED=yes

matrix:
  include:
    - python: 3.6
      env: TOXENV=cpython-3.6
    - python: 3.7
      env: TOXENV=cpython-3.7

before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update
  - sudo apt-get install -y flatbuffers
  - pip install poetry
install:
  - python -m pip install -U tox
script: tox
